# Site Settings
title: Paul karikari| Resume | CV
url: 'https://paulkarikari.github.io/'
baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Paul Karikari
tagline: "Software Engineer,     
Deep Learning and Data Engineering"
pic: 'bio-photo.jpg'  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "As a senior software engineer, I have had experience working in various roles in the tech industry.
I have built scalable software products ranging from web applications to AI( deep learning) enabled applications as well as data pipelines for data-centered products.
<br>
I have a strong understanding of deep learning algorithms with keen interest and passion for building intelligent systems with deep learning.
I'm familiar with various deep learning techniques such as DNN, CNN, LSTM, etc used in solving problems in Computer Vision, NLP, and Time-series prediction.
<br>
I have a solid grasp of the entire machine learning workflow, and I have built data pipelines to get data from various data sources to the expected form for data science and machine learning use cases.
I maintain high data quality standards by including data quality checks in the pipelines I build.
<br>
I'm very passionate about my craft and the tech community, I contribute to open source projects with multiple pull-request merged and also
I'm the Founder and Tech community builder at <a href='https://www.meetup.com/Python-Luxembourg/' target='_blank'>PyLuxembourg.</a>
"

#sidebar links
email: paulkarikari1@gmail.com
phone: +352 621 752 087
website: paulkarikari.com #do not add http://
linkedin: paulkarikari
github: paulkarikari
twitter: '@KofiCodes'
location: Luxembourg, Europe
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
