# Site Settings
title: Paul karikari (koficodes) | Resume | CV
url: 'https://koficodes.github.io/'
baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Paul Karikari
tagline: Software Engineer
pic: 'bio-photo.jpg'  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A well-grounded full-stack engineer with a taste for building quality software products.  
Constant learner and a track record of solving problems with technology. 
Extensive experience in implementing complex software projects to make life better for clients and Users.'

#sidebar links
email: paulkarikari1@gmail.com
phone: +39 351 025 7888
website: koficodes.github.io #do not add http://
linkedin: paulkarikari
github: koficodes
twitter: '@KofiCodes'
location: Camerino, Italy
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
